package com.github.mengweijin.quietly.system.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import com.baomidou.mybatisplus.annotation.TableField;
import com.github.mengweijin.quickboot.mybatis.entity.BaseEntity;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;

/**
 * <p>
 * test step
 * </p>
 *
 * @author mengweijin
 * @since 2022-04-30
 */
@Data
@EqualsAndHashCode(callSuper = true)
@Accessors(chain = true)
@TableName("QTL_STEP")
public class Step extends BaseEntity {

    private static final long serialVersionUID = 1L;

    /**
     * The table QTL_API_CASE id
     */
    @TableField("CASE_ID")
    private Long caseId;

    /**
     * The execution order of steps, generated by the program.
     */
    @TableField("SEQ")
    private Integer seq;

    /**
     * Y, N
     */
    @TableField("ENABLED")
    private String enabled;

    /**
     * spring bean name for QuietlyStep.java children instance.
     */
    @TableField("STEP_DEFINITION")
    private String stepDefinition;

    /**
     * action or assert key. E.g.: init data sql; json path key;
     */
    @TableField("ACTION_OR_ASSERT_KEY")
    private String actionOrAssertKey;

    /**
     * expect value.
     */
    @TableField("EXPECT_VALUE")
    private String expectValue;

    /**
     * Actual value
     */
    @TableField("ACTUAL_VALUE")
    private String actualValue;

}
