server:
  servlet:
    context-path: /quietly
quietly:
  #step-package: com.github.mengweijin.quietly.step
  test:
    datasource:
      url: jdbc:h2:file:./h2/quickboot;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
      username: sa
      password: