drop table IF EXISTS QTL_DATA_SOURCE;
create TABLE QTL_DATA_SOURCE (
  id bigint NOT NULL COMMENT 'id',
  url varchar(200) NOT NULL COMMENT 'jdbc url',
  username varchar(60) NOT NULL COMMENT 'Database username',
  password varchar(60) DEFAULT NULL COMMENT 'Database password',
  deleted int(4) DEFAULT 0 COMMENT 'Logic delete,（0 no delete; 1 deleted）',
  create_by varchar(64) NULL COMMENT 'Creator',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'creation time',
  update_by varchar(64) NULL COMMENT 'Revisor',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON update CURRENT_TIMESTAMP COMMENT 'Revisor time',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Data source info';


drop table IF EXISTS QTL_API;
create TABLE QTL_API (
  id bigint NOT NULL COMMENT 'primary key id',
  url varchar(500) NULL COMMENT 'test api url',
  request_type varchar(10) NOT NULL COMMENT 'HTTP request type: GET/POST/PUT/DELETE',
  login_url varchar(500) NULL COMMENT 'get token url',
  login_request_type varchar(10) NULL COMMENT 'HTTP request type: GET/POST',
  login_args varchar(100) NULL COMMENT 'get token args json',
  create_by varchar(64) NULL COMMENT 'Creator',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'creation time',
  update_by varchar(64) NULL COMMENT 'Revisor',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON update CURRENT_TIMESTAMP COMMENT 'Revisor time',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='application program interface';


drop table IF EXISTS QTL_API_CASE;
create TABLE QTL_API_CASE (
  id bigint NOT NULL COMMENT 'id',
  case_name varchar(100) NOT NULL COMMENT 'test case name',
  description varchar(500) NOT NULL COMMENT 'test case description',
  api_id bigint NOT NULL COMMENT 'The table QTL_API id',
  url_args varchar(1000) NULL COMMENT 'url args JSON string',
  request_args varchar(1000) NULL COMMENT 'request body args JSON string',
  status varchar(20) NOT NULL DEFAULT 'CREATED' COMMENT 'CaseStatus enum.',
  feature_content varchar NULL COMMENT 'feature file content',
  exception varchar NULL COMMENT 'test case failed exception message.',
  create_by varchar(64) NULL COMMENT 'Creator',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'creation time',
  update_by varchar(64) NULL COMMENT 'Revisor',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON update CURRENT_TIMESTAMP COMMENT 'Revisor time',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='test case';


drop table IF EXISTS QTL_STEP;
create TABLE QTL_STEP (
  id bigint NOT NULL COMMENT 'id',
  case_id bigint NOT NULL COMMENT 'The table QTL_API_CASE id',
  seq int(4) NOT NULL DEFAULT 0 COMMENT 'The execution order of steps, generated by the program.',
  enabled char(1) NOT NULL DEFAULT 'Y' COMMENT 'Y, N',
  step_definition varchar(100) NOT NULL COMMENT 'spring bean name for QuietlyStep.java children instance.',
  action_or_assert_key varchar(500) NULL COMMENT 'action or assert key. E.g.: init data sql; json path key;',
  expect_value varchar NULL COMMENT 'expect value.',
  actual_value varchar NULL COMMENT 'Actual value',
  create_by varchar(64) NULL COMMENT 'Creator',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'creation time',
  update_by varchar(64) NULL COMMENT 'Revisor',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON update CURRENT_TIMESTAMP COMMENT 'Revisor time',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='test step';

